### PR TITLE
Rename OxyPlot.WindowsUniversal to OxyPlot.Windows

### PR DESCRIPTION
**Pull request by objorke**
As described in #242.
Also marks OxyPlot and OxyPlot.Mobile as obsolete.

### CODE REVIEW

**Comment by objorke** [comment]
@tibel can you review this?

**Comment by tibel** [comment]
Looks good :+1: 

TODO:
- update build scripts containing OxyPlot.WindowsUniversal (e.g build-mobile.cmd)
- remove OxyPlot.WindowsUniversal from OxyPlot.Xamarin.Forms.nuspec

**Comment by objorke** [comment]
@tibel I have updated the two files mentioned!

**Comment by tibel** [comment]
You are right. So existing users can update to the new package.

**Comment by tibel** [comment]
@objorke Everything looks good. I think it is ready to merge.

**Comment by objorke** [comment]
OK, I can push the merge button myself, but isn't it a good principle to never merge your own pull requests?

**Comment by tibel** [comment]
You are right. Four-eye-principle is a good idea for bigger changes.
I just didn't know you wanted to play it this way.

**Pull request merged**
