### PR TITLE
Fix a problem with inifity size polyline

### PR DESCRIPTION
**Pull request by mennodeij**
Issue #1303 

The problem solved is illustrated in PlotViewTests.cs:110-136.
In short, when plotting large Y-ranges, the WPF measuring of a `System.Windows.Shapes.Polyline` may return an invalid size containing `double.Infinity`. This has been fixed by reimplementing the polyline class with a fix in `MeasureOverride` (the WPF implementation is `sealed` unfortunately, so no inheritance could be used).

### Checklist

- [x] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- Replace the `System.Windows.Shapes.Polyline` with a fixed re-implementation (`Polyline2`). 

@oxyplot/admins

### CODE REVIEW

**Comment by mennodeij** [comment]
If other platforms handle this without single precision overflow, the only fix should be in the WPF platform. Is there a way to test this in CI on all platforms? I do not have access to other platforms other than GTK.

**Comment by objorke** [comment]
I would guess UWP and maybe Xamarin.Forms have similar issues. It probably needs to be tested manually.
I still think this could be solved within the axis classes - if the coordinates transformed into "screen space" is unreasonable large, they could be "clipped" or ignored?

**Comment by objorke** [comment]
I suggest an alternative solution in #1365 

The WPF Polyline should not be modified, I think this can be solved in OxyPlot.Wpf.

**Comment by objorke** [comment]
Merged #1365

**Pull request closed without merging**
