### PR TITLE
#759 fixed test to run on all versions of windows

### PR DESCRIPTION
**Pull request by benjaminrupp**
added test font

### CODE REVIEW

**Comment by objorke** [comment]
the broken build seems to be a Xamarin license issue. I will investigate it

**Comment by objorke** [comment]
now it seems like gitversion is the problem.

**Comment by objorke** [comment]
should the font be installed before running the test?

**Comment by benjaminrupp** [comment]
I did not install the font on my system. I just copied it to the output folder by the setting "copy if newer".

**Comment by benjaminrupp** [comment]
I have no idea what's the problem with gitversion. Do I have to change something on my commit?

**Comment by objorke** [comment]
I tried pack uris for the fonts. See #775

**Comment by objorke** [comment]
The builds never succeeded, right? Should we close this PR?

**Comment by benjaminrupp** [comment]
I have no idea why this is not running on the build server.
It is running correctly on my win 7 developer pc and also on my windows 2012 team city server.
If i am using the old test its not running on win 2012 cause the microsoft changed the font with win 8 and all following windows versions.

**Comment by tibel** [comment]
We fixed some issues related to the build server in the meantime.
Try to rebase your changes so the build server takes another try.
When it still fails, I will close this pull request.

**Comment by benjaminrupp** [comment]
Hi tibel,

the AppVeyor server is behaving strange. 
Yesterday it was running. I had just one bug in my test. Now it is not running anymore. But my test is okay now. Its running local and on my own build server.

I just don't now what I should do to fix the AppVeyor.

Regards

Benjamin

**Comment by tibel** [comment]
According to the build log it seems that _gitversion_ has some problem.

You can try to use newer _gitversion_ by updating `appveyor.yml` and set version to `3.5.2`.
I haven't tested this, but worth to try.

**Comment by benjaminrupp** [comment]
I tried. But it is not working :-(

**Comment by objorke** [comment]
The unit tests are failing in the last build.
Are the tests too strict? Should we not ask for pixel perfect?

**Comment by benjaminrupp** [comment]
If the Tests are failing, then the test Font is not used. Arial is in this Case used as default. I am not sure why the Test does not find the fonts. Unfortunately, i broke my arm and i will not be able to access my computer for the next  Weeks. I will take care later.

**Comment by objorke** [comment]
Can't merge this since it breaks the appveyor build.
Maybe you could ignore the tests on the Win2012 server?

**Pull request closed without merging**
