### PR TITLE
Fix NullReferenceException

### PR DESCRIPTION
**Pull request by karlmtc**
If ActualPoints is null, we can't access the count. We need to check for null first.

### CODE REVIEW

**Comment by objorke** [comment]
I see this is consistent with the implementation in `LineSeries`, so let us accept this! :-)
Are you included in the contributors list?
The change log should also be updated!

**Comment by karlmtc** [comment]
I think it's done. I'm fairly new to github so please check if it's all ok. Thank you for your time.

**Comment by objorke** [comment]
Please remove the merge commit, squash the 5 other commits into one (use git rebase interactively and git push -f)
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by objorke** [comment]
I can fix this for you.

**Comment by objorke** [comment]
Please have a look at #605 and #606. 
First I created the issue. Then I removed the merge commit and rebased & squashed the other ones. Changed the commit message to include #605.

**Comment by objorke** [comment]
Merged in #606

**Pull request closed without merging**
