### PR TITLE
SharpDX based renderer

### PR DESCRIPTION
**Pull request by Soarc**
Implemented  #124 .

I have been implemented SharpDX renderContext for OxyPlot and created WPF control based on SharpDX renderer. 
Also i`ve added PlotHeight and PlotWidth properties and scrolling ability to WPF control. So now you can set exact heigth for plot. This can be useful, if someone (like me), want to have multiple plots with shared axis. And it might not fit on the screen.

I have troubles with stylecop and squashing history. Can i get help with this?

### Checklist

- [ ] I have included examples or tests
- [+ ] I have updated the change log
- [ +] I am listed in the CONTRIBUTORS file
- [ ] I have cleaned up the commit history (use rebase and squash)

### CODE REVIEW

**Comment by tibel** [comment]
Great. Can we use SharpDX for Universal Windows Apps too?

**Comment by Soarc** [comment]
Yes, it should be possible. I implemented IRenderContext in separate project for this purpose. The only part, that i`m not sure how to port is D3DImage object, which is WPF specific. The PlotView can be ported i think.

**Comment by Soarc** [comment]
I dig a bit deeper: I found analogue for ID3DImage WPF class: SwapChainPanel,

But i can`t find any analogue for IScrollInfo. So there might be problems with porting PlotHeight/PlotWidth properties.

**Comment by tibel** [comment]
I have merged you branch.

A few notes:
- a pull request should contain one topic only (PlotHeight/PlotWidth???)
- I have created OxyPlot.SharpDX.Windows project
- both WPF and UAP (Windows) use a shared project that contain the actual code
- what is your change with PlotHeight/PlotWidth about? it should be a separate issue.
- what is with `CacherRenderContext` vs. `SharpDXRenderContext`. what is used? remove one?

I think we should continue the to discuss the next steps on #124 

Thanks for your contribution! Great work.

**Pull request merged**
