### PR TITLE
PieSeries for WPF

### LINKED ISSUE #878: Enable pie series to be added via XAML
### Feature description

I'd like to create a `PieSeries` via XAML (WPF), so that I don't have to put together a `PlotModel` in my view model.

Basically, I would like to be able to do something similar to [this example](https://github.com/oxyplot/oxyplot/blob/develop/Source/Examples/WPF/WpfExamples/Examples/BarSeriesDemo/MainWindow.xaml#L14-L18).

I noticed there already have been some requests for this since 2014, and I'd be happy to help you out with the implementation.

### PR DESCRIPTION
**Pull request by inosik**
Fixes #878.

### Checklist

- [x] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

Adds a wrapper for the `PieSeries` class to OxyPlot.Wpf.

@oxyplot/admins

### CODE REVIEW

**Comment by objorke** [comment]
Excellent! Thanks for contributing. I will squash the commits before merging.

**Comment by inosik** [comment]
Great, thank you, @objorke! When this will be available via NuGet?

**Comment by objorke** [comment]
we use myget for the CI packages. Main release will be pushed to NuGet!

status of v1:
https://github.com/oxyplot/oxyplot/milestones/v1.0

**Comment by inosik** [comment]
I'll keep my eyes open :wink: 

I found the CI feed at `https://www.myget.org/F/oxyplot/`, maybe this should be documented somewhere?

**Comment by objorke** [comment]
absolutely. There should also be an announcement on www.oxyplot.org. I can do it hopefully next week!

**Pull request merged**
