### PR TITLE
Fix small typo in Properties, additional interpolation algorithm

### PR DESCRIPTION
**Pull request by gro-ove**

### CODE REVIEW

**Comment by gro-ove** [comment]
#494

How it looks in action:
image

Hmm, sorry, but why have checks failed? I guess I shouldn’t change WPF library at the same time as the main one?

**Comment by objorke** [comment]
Very good! But we need some examples! It would be great to have the 5 plots in the ExampleLibrary.
I also think we should refactor the `InterpolationAlgorithm` to a more extensible data structure at some point. e.g. create an `IInterpolationAlgorithm` interface and use that for the `InterpolationAlgorithm` property.
Will you add the examples before I merge? And what about refactoring the enum?

**Comment by gro-ove** [comment]
@objorke yes, of course! But just to be sure (sorry, I don’t have much experience):

- Replace `InterpolationAlgorithm` with `IInterpolationAlgorithm`;

- Transform `CanonicalSplineHelper` from an internal static class to `public class CanonicalSpline : IInterpolationAlgorithm`;

- Add something like `BaseCatmulRomSpline : IInterpolationAlgorithm` with `CatmullRom`, `UniformCatmullRom` and `ChordalCatmullRom` as children classes;

So, it will be used like `lineSeries.InterpolationAlgorithm = new CatmullRom()`, is it right?

**Comment by objorke** [comment]
yes, this is exactly what I meant.

To make it easy to use we could also create a static class
``` cs
public static class InterpolationAlgorithms {
    public static IInterpolationAlgorithm CatmullRom { get; } = new CatmullRom();
}
```

then we could also write `lineSeries.InterpolationAlgorithm = InterpolationAlgorithms.CatmullRom;`

With this change, I think the `Smooth` property should be marked obsolete
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Series/LineSeries.cs#L209
something like:
```cs
[Obsolete("Use the InterpolationAlgorithm property instead")]
public bool Smooth {
    get { return this.InterpolationAlgorithm is CanonicalSpline; }
    set { this.InterpolationAlgorithm = value ? InterpolationAlgorithms.CanonicalSpline : null; }
}
```

**Comment by objorke** [comment]
this looks good! thanks!!

**Pull request merged**
