### PR TITLE
Added WPF Wrapper for BoxPlot

### PR DESCRIPTION
**Pull request by stefan-schweiger**
For more info see: https://github.com/oxyplot/oxyplot/issues/425

Basically I borrowed some code from BarSeries for the ItemsSource stuff and added a WPF wrapper.

### CODE REVIEW

**Comment by objorke** [comment]
Great! 
1. Can you please squash the commits (e.g. "fix stylecop stuff" and reverts should not be part of the commit history). 
2. Update the chang log
3. Update CONTRIBUTORS/AUTHORS if you are not already listed!

**Comment by stefan-schweiger** [comment]
Ok I hope now everything is fine for you, as the whole process was like this for me:

noidea

**Comment by stefan-schweiger** [comment]
once this gets merged, I also have a pull request in the pipeline to also display the mean value.

**Comment by objorke** [comment]
Looks good now! Thanks for contributing!

**Pull request merged**
