### PR TITLE
Please ignore. Just a test. Will close shortly.

### PR DESCRIPTION
**Pull request by shoelzer**
Enables checked math. I'm doing this so I can submit a PR on Github and have Appveyor run all
the build tests. Let's see if anything breaks.

### CODE REVIEW

**Comment by shoelzer** [comment]
All tests passed which is good to see. The checked math option could be enabled permanently, but it's probably not necessary. Closing this PR.

**Comment by objorke** [comment]
Did you include the flag on the portable projects? I think those are the projects that are used by the test project (OxyPlot.Tests.csproj depends on OxyPlot.csproj and ExampleLibrary.csproj)

**Comment by objorke** [comment]
Will there be a performance hit by enabling this option?

**Comment by shoelzer** [comment]
I missed the portable projects earlier. I don't fully understand how things are organized. I'll try again with a new PR.

There will be a performance hit with checked math. It's really hard for me to say if it will be negligible, severe, or somewhere in the middle for OxyPlot. Basically all math operations are checked for overflow and underflow. In my (limited) experience, the effect if negligible except in tight loops.

**Pull request closed without merging**
