### PR TITLE
Updated the changelog for my changes and made the Mobile NuGet empty

### PR DESCRIPTION
**Pull request by mattleibow**
Based on the changes in #362 :

 - Added the OxyPlot.Mobile NuGet
 - OxyPlot.Xamarin.Forms now depends on OxyPlot.Mobile

The change in the android target platform to 2.3 was only for the ExampleBrowser app, not the library - which is already done.

### CODE REVIEW

**Comment by mattleibow** [comment]
Rather than adding the assemblies to a new NuGet, create an empty NuGet to:

 - avoid duplications of the various platforms
 - avoid breaking existing apps

**Comment by objorke** [comment]
To reduce the number of packages, I think it would be better to reverse the dependencies (e.g. OxyPlot.iOS depends on OxyPlot.Mobile) and mark the old packages obsolete. Then after some time, unlist all the obsolete packages.

**Comment by objorke** [comment]
I committed the modifications to the change log

**Comment by mattleibow** [comment]
OK, that seems valid.

**Pull request closed without merging**
