### PR TITLE
Add Windows Universal (uap10) project

### PR DESCRIPTION
**Pull request by objorke**
To solve issue #615

### CODE REVIEW

**Comment by objorke** [comment]
nuget restore fails on appveyor. No problems locally. I don't understand... :-)

**Comment by csabar** [comment]
I was unable to build your files. The problem is that Visual Studio Express for Windows 10 is unable to load project "OxyPlot" as reference. I think you need to create a new solution file, which can be loaded with Visual Studio for Windows 10.

**Comment by objorke** [comment]
The build was OK locally with Visual Studo 2015. The solution should be OK, but I don´t understand why nuget restore fails on appveyor for the Windows10 project.

**Comment by csabar** [comment]
Even if you have correct build at your computer, I was unable to build your commit and maybe that is why AppVeyor build has also failed. The OxyPlot.csproj needs to be updated to support UWP platform. Maybe you can create new project from scratch and merge with current project or make a copy with different name and use this guide: https://msdn.microsoft.com/en-us/library/mt148501.aspx
I think the problem might be with AnyCpu because it is mentioned in AppVeyor message and according to the guide:
> 8 . Find <PropertyGroup> elements that are configured for the AnyCPU platform as part of the Condition attribute. Remove these elements and all of their children. AnyCPU is not supported for Windows 10 apps in Visual Studio 2015. 

But I'm just guessing the reason. I don't know how the AppVeyor works.

**Comment by objorke** [comment]
Thanks for the link! I will try to create a UWP version of the core project as you suggest!

**Comment by objorke** [comment]
I had some progress yesterday, now there is a netcore 4.5.1 error.

**Comment by objorke** [comment]
http://help.appveyor.com/discussions/problems/2993-uwp-test-assembly-build-failing
http://help.appveyor.com/discussions/problems/2702-vs2015-uwp-project
http://help.appveyor.com/discussions/questions/1320-windows-10-support

**Pull request merged**
