### PR TITLE
Improved the animations example so it could be used in PCL as well

### PR DESCRIPTION
**Pull request by GeertvanHorrik**
I am not done yet, but you can track progress here. I have improved the example a bit with custom IEasingFunction implementations so this can be used on all platforms. I will keep it for WPF for now so I can implement different kind of animations. Once it's all done, the extensions should be directly usable on other platforms.

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
oxyplot_animations

**Comment by objorke** [comment]
Cool! The portable animation code is a good candidate for the Oxyplot.Contrib package, I think!

**Comment by GeertvanHorrik** [comment]
oxyplot_animations_lineseries

**Comment by GeertvanHorrik** [comment]
oxyplot_animations_areaseries

**Comment by GeertvanHorrik** [comment]
I think this is it for now, it's ready for review.

**Comment by GeertvanHorrik** [comment]
Based on some feedback, I have added the option to specify how much % of the animation the x and y axes should animate:

oxyplot_animations_customization

**Comment by objorke** [comment]
Need to get the build up and running again soon...

**Comment by objorke** [comment]
This looks very good! I´ll merge it!

**Pull request merged**
