### PR TITLE
Fix OpenStreetMap example (#1642)

### LINKED ISSUE #1642: TileMapAnnotation requires custom user agent on openstreet map.
### Steps to reproduce

1. Open Oxyplot.WindowsForms Example browser
2. Exceptions are thrown when loading the data 429

### Expected behaviour

Should show the map

### Actual behaviour
no Map

### Solution
Add a UserAgent to the request and limit the threads to max 2.

They updated their usage policy
https://operations.osmfoundation.org/policies/tiles/

### PR DESCRIPTION
**Pull request by VisualMelon**
Fixes #1642

### Checklist

- [ ] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- As per the suggestions in #1642 and the OSM policy documentation (https://operations.osmfoundation.org/policies/tiles/)
  - Limits the number of download threads for OSM to 2
  - Adds a configurable UserAgent defaulting to "OxyPlotExampleLibrary"

Setting the user agent is a bit unpleasant, but has been tested with the NET Framework 4.6.1 and NET Core 3.1 WinForms example browser.

@oxyplot/admins

### CODE REVIEW

**Comment by VisualMelon** [comment]
I'm not sure what the rules on User-Agents for non-browsers are; someone with some awareness of web technologies might want to take a look. I'm also tempted to suggest we remove the tile map examples for the automated tests regardless of whether they work or not, because they depend on an external resource (and the downloading is the only bit isn't covered by other components).

**Comment by Jonarw** [comment]
Yes I think it is a good idea to remove them from unit tests - if for some reason the tile server is not reachable we don't want our tests to fail because of that.

Unfortunately, I am not very knowledgeable about web technologies, but as long as it works I guess it's fine.

**Comment by VisualMelon** [comment]
@Jonarw had a go at that. It's a bit ugly, but I don't know how much that matters.

**Comment by Jonarw** [comment]
Looks fine to me, good to go from your side?

**Comment by VisualMelon** [comment]
@Jonarw If you don't think the `ForAutomatedTest` postfix is too hideous, I have nothing more to add.

**Comment by VisualMelon** [comment]
Actually, let me fix a couple of formatting things...

**Comment by objorke** [comment]
See also #1400

**Pull request merged**
