### PR TITLE
"This PlotModel is already in use by some other PlotView control"

### PR DESCRIPTION
**Pull request by icerocker**
Ref. issue [#497](https://github.com/oxyplot/oxyplot/issues/497). I experience the same issue when using oxyplot in a WPF DataGrid DataTemplate.

I've added a demo application which can trigger this bug. The application lists 10 rows in a DataGrid. Expand multiple rows (Ctrl+Click). When scrolling (either with the scroll wheel or using the scroll bar) the application crashes with "XamlParseException - This PlotModel is already in use by some other PlotView control". This application only instanciates a PlotModel, nothing else oxyplot related to keep it as simple as possible. I did get this exception when running a more complete program too.

(Not sure if this is the correct way of reporting a bug with code attached)

### CODE REVIEW

**Comment by objorke** [comment]
Thanks for creating a good example!
I have some requests:
- move the code into the WpfExamples project (https://github.com/oxyplot/oxyplot/tree/develop/Source/Examples/WPF/WpfExamples/Examples) - we must avoid "project bloat" in the solution. In the past, all these examples were different projects and the solution took much longer time to build
- do not depend on NuGet packages inside this repository (dependencies will already be there for the WpxExamples project)

**Comment by objorke** [comment]
I think you have to rebase and `git push -f` this PR

**Comment by objorke** [comment]
The code must be added to the WpfExamples project.

**Comment by tibel** [comment]
I have integrated your example in WpfExamples

**Pull request closed without merging**
