### PR TITLE
refactor: Refactored to use dependency-property-generator.

### PR DESCRIPTION
**Pull request by HavenDV**
Fixes # .

### Checklist

- [ ] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- Switching to DependencyPropertyGenerator(according changes in H.OxyPlot - https://github.com/HavenDV/H.OxyPlot/commit/486ef866508b64611738518736db8f01a5132de3)
-
-

@oxyplot/admins

### CODE REVIEW

**Comment by HavenDV** [comment]
You can verify that the generated code is equivalent by opening:
image

**Comment by VisualMelon** [comment]
I'm not sure if this is a good idea: these generators are great for RAD and keeping things clean, but here we are losing the comments (though none of them in this case are all that inspiring, and indeed some are wrong) and it all seems a bit much for not much simplification in this case (most of these files have had about 3 changes since they were laid down in 2014; OxyPlot.Contrib would be a different matter).

This is not to say I'm opposed to this change, but I probably shan't merge it by myself because it adds additional third-party dependencies.

**Comment by HavenDV** [comment]
I agree, there are pros and cons here, so feel free to close this PR if it doesn't seem right for this library.
xml documentation can also be added via this generator, either via the Description property (which will also generate an attribute for the designer) or raw. I didn't add this because it seemed to me that there was documentation here that didn't say anything. But I missed the point that there is some documentation here that makes sense.

**Comment by HavenDV** [comment]
I've updated the PR to be fully consistent with the current documentation:
For DependencyProperties "Identifies" documentation is generated automatically.
For regular properties, the value is taken from the Description attribute.

**Comment by VisualMelon** [comment]
Having the comments is a big plus for me. I'm certainly not going to close this, as one of the other maintainers may have a more positive reactive and I don't want to bury it, but as it does add 'third party' dependencies I'd want to defer to @objorke .

**Comment by objorke** [comment]
Thanks @HavenDV for creating the PR, but I am also negative to merging this PR.

Dependencies should be avoided, both for maintenance and security perspectives. I see how dependency-property-generator can simplify code, but I don't think it adds enough value to bring in a dependency, even if it is a developmentDependency.

See also #39, I think that issue is similar - syncing dependency properties to the "core" model.

**Comment by HavenDV** [comment]
Thank you for reviewing this PR. It's ok that it's rejected, your reasons are quite understandable.
P.S. Regarding the specified issue - the generator just made the dependency property code "cross-platform" (more precisely, it generated its own unique code for each platform, but keeping the same behavior between them)

**Pull request closed without merging**
