### PR TITLE
Upgrade to .NET Core 3.1 (#1488)

### LINKED ISSUE #1483: Change order of TargetFrameworks in OxyPlot.Wpf.csproj
Currently when referencing the OxyPlot.Wpf project directly from a .NET Framework project Visual Studio displays a warning "The project 'OxyPlot.Wpf' cannot be referenced. The referenced project is targeted to a different framework family (.NETCoreApp)".

It is possible to [prevent this warning](https://developercommunity.visualstudio.com/content/problem/710554/build-warning-when-referencing-multitarget-project.html) by changing the order of the target frameworks.

I've tested it and by changing [the line in the project file](https://github.com/objorke/oxyplot/blob/4daca0ae13667c5a97ad5dcec425f33a9ff7fd49/Source/OxyPlot.Wpf/OxyPlot.Wpf.csproj#L3) from

    <TargetFrameworks>netcoreapp3.0;net45;net40</TargetFrameworks>

to

    <TargetFrameworks>net45;net40;netcoreapp3.0</TargetFrameworks>

the warning disappears.

This might apply to more project files but the core project (OxyPlot.csproj) is not affected.

### LINKED ISSUE #1488: Upgrade to netcoreapp3.1
[.NET Core 3.0 reaches end of Life today](https://devblogs.microsoft.com/dotnet/net-core-3-0-end-of-life/). We should upgrade all relevant packages to .NET Core 3.1, which is a LTS release. Upgrading should be straightforward I think. This affects:

- OxyPlot.WPF
- OxyPlot.WindowsForms

### PR DESCRIPTION
**Pull request by Jonarw**
Fixes #1488.
Also fixes #1483.

### Checklist

- [ ] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- Update all `netcoreapp3.0` targets to `netcoreapp3.1`
- Change target order so `net4xx` targets are listed before `netcoreapp3.x` targets

Did I miss anything?

@oxyplot/admins

### CODE REVIEW

**Comment by Jonarw** [comment]
Azure Pipelines Build seems to fail for some reason... I don't really know what to do about this. @objorke could you take a look? Thanks!

**Comment by objorke** [comment]
The exceptions are thrown in a unit test in OxyPlot.Wpf.Tests
https://dev.azure.com/oxyplot/OxyPlot/_build/results?buildId=177&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7bfb7e0f-549d-5929-c603-6e8046613b9e

The appveyor build seems to work:
https://ci.appveyor.com/project/objorke/oxyplot/builds/31204899

**Comment by Jonarw** [comment]
Is it actually a failed unit test? Yes, there is an exception thrown during testing, but no test is reported as failed... On my machine all test pass (except `ExportPngAndCompareWithBaseline`, but I guess that one is tricky anyway and does actually pass on Azure).

I don't really know what to do about this. Can we just ignore this error?

**Comment by Jonarw** [comment]
I am going to go ahead and merge this, considering that the AppVeyor build works fine.

**Pull request merged**
