### PR TITLE
Add Avalonia Renderer

### LINKED ISSUE #941: Avalonia support
There is very promising cross platrofm UI framework called Avalonia

https://github.com/AvaloniaUI/Avalonia

> A multi-platform .NET UI framework. It can run on Windows, Linux, Mac OS X, iOS and Android. Avalonia is a multi-platform windowing toolkit - somewhat like WPF - that is intended to be multi- platform. It supports XAML, lookless controls and a flexible styling system, and runs on Windows using Direct2D and other operating systems using Gtk & Cairo.

This ticket is about adding OxyPlot support for it

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #941  .

### Checklist

- [x] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- Add Avalonia based render
- Add samples (generally copied from WPF)

@oxyplot/admins

### CODE REVIEW

**Comment by objorke** [comment]
Wow, this is very cool! I am looking forward to merge this!
I have some comments
1. Doesn't render correctly on my machine. Lines seem to be missing
2. I am a bit worried about maintaining the AvaloniaExamples and the XAML classes for series, axes, annotations - the source code seems to be 99% duplicate of the WPF code. I think it would be better to share code, or remove this functionality/examples...
3. It would be great to see the ExampleBrowser ported! I would prefer that one over the AvaloniaExamples.
4. I see some lagging when panning in the example applications, is this an issue with Avalonia?

**Comment by objorke** [comment]
This is how the BarSeriesDemo in the AvaloniaExamples look on my machine:
image
I was expecting to see some lines on the axes and around the tab control.

**Comment by jkoritzinsky** [comment]
1. That might be a Direct2D1-renderer problem. I'll try it out with different rendering backends and let you know.
2. The APIs of WPF and Avalonia are just different enough to make it very difficult to share without just code-genning all of the `DependencyProperty`/`AvaloniaProperty`s. I actually wrote a Roslyn analyzer and code fix to port this over with.
3. I'll take a look at ExampleBrowser and try to port it over when I get a chance!
4. That's an Avalonia perf problem that's been reported.

**Comment by jkoritzinsky** [comment]
@objorke I took a look at the missing lines. It's an issue in Avalonia's Direct2D1 rendering subsystem. It works in the Skia subsystem.

**Comment by objorke** [comment]
good! the AvaloniaExamples app works now!

**Pull request merged**
