### PR TITLE
Transposable annotations

### LINKED ISSUE #1417: Add support for transposable Annotations
### Feature description

Now that we have support for transposable `XYAxisSeries`, it would be nice if annotations also supported this. Some initial thoughts:

- To avoid code duplication, we could introduce a `ITransposablePlotElement` interface which `XYAxisSeries` and `Annotation` would both implement. This would expose the `XAxis` and `YAxis`. We could then move the `Transform` and `Orientate` functions to extension methods, something like:
```
public static ScreenPoint Orientate(this ITransposablePlotElement element, ScreenPoint point)
{
    return element.IsTransposed() ? new ScreenPoint(point.Y, point.X) : point;
}
```

- Should `TextRotation` be influenced by transposition? For now I don't think it should be - consistently transposed text would be mirrored and that is hardly what anyone would want. So maybe for text only position and alignment should be affected by transposition?

I will start working on this, if there are any additional considerations, please let me know.

### PR DESCRIPTION
**Pull request by Jonarw**
Fixes #1417 .

### Checklist

- [x] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- Add Support for transposable Annotations
- To avoid code duplication, introduce interface `ITransposablePlotElement` (implemented by `XYAxisSeries` and `Annotation`)

@oxyplot/admins

### CODE REVIEW

**Comment by objorke** [comment]
Thanks for the contribution! This looks very good!

**Comment by objorke** [comment]
Is it worth explaining how this works in the documentation?

**Comment by objorke** [comment]
I was also thinking if we really need the new interface - could it simply be merged with `IPlotElement`? I am aware of the interface-segregation principle ISP, but also worrying about creating "too small" interfaces - which could be YAGNI.. Keep it simple :-)

**Comment by Jonarw** [comment]
I think there might be some issues with merging the new interface with `IPlotElement`. First of all, just semantically not all `IPlotElement`s are transposable, think of `PieSeries` or polar plots for example. Also not all `IPlotElement`s even have `XAxis` and `YAxis` properties that could implement the interface - for example all Axes classes themselves.

**Pull request merged**
