### PR TITLE
Doc generator

### PR DESCRIPTION
**Pull request by Peter-B-**
### Checklist

- [ ] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

I imported the ExampleGenerator project from the ```documentation-examples``` repository, as proposed [as proposed in a pull request there](https://github.com/oxyplot/documentation-examples/pull/21).

I introduced a new ```DocumentationExample``` attribute and marked some basic plots with it.

If this pull request is accepted and the documentation samples are moved here, I can port some of the old documentation examples to this repository.

@oxyplot/admins

### CODE REVIEW

**Comment by objorke** [comment]
I would prefer truepng not to be included in the repository. I think this should be a prerequisite for the ExampleGenerator (should be in PATH). https://chocolatey.org/packages/truepng

Can you remove truepng and rebase?

**Comment by objorke** [comment]
Can you move the ExampleGenerator into the `Examples` folder?

**Comment by Peter-B-** [comment]
This is a great idea. I don't like having binaries lying around in git repos.

I also moved the the project into ```Examples```. However, I left the project in the ```Documentation``` solution folder. The ```Examples.csproj``` is in ```Tests```, which does not really fit. Should I clean that up?

**Comment by objorke** [comment]
yes, please clean that up.
Should this PR be squashed, or did you get truepng out of the commit history?

**Comment by Peter-B-** [comment]
Done.

There is no TruePNG binary in the commit history. I reverted to the commit before and cherry picked all following commits.

**Comment by objorke** [comment]
Thanks!

**Pull request merged**
