### PR TITLE
Fix tracker position in WinForms

### PR DESCRIPTION
**Pull request by iainnicol**
This was fun to debug!  I couldn't see the tracker.  My first, incorrect, guess was that I had to set the TrackerFormatString.

### CODE REVIEW

**Comment by objorke** [comment]
Please create an issue first describing the problem! Can we see it in any of the existing examples? Otherwise create a new example how to reproduce the error. Please include the issue # in the commit description and PR description. Update the change log and contributor files. Cheers!

**Comment by objorke** [comment]
Almost good to go! Just update under the CHANGELOG.md fixed section!

**Comment by objorke** [comment]
#455

**Comment by objorke** [comment]
This solves #455

**Comment by iainnicol** [comment]
@objorke Thanks for the review.  Change log updated.  Sorry for my poor reading comprehension today: I see you had asked me to do that earlier.

**Comment by objorke** [comment]
Thanks for contributing to the project!

**Pull request merged**
