### PR TITLE
Place label below negative ColumnSeries (#1119)

### LINKED ISSUE #1119: Oxyplot WPF ColumnSeries labelplacement with negative values
Label placement with columnseries on negative values.

Why label placement (set to outside) are on the "zero line" and not on top of columns as it does for positive values.

Actual 
labelplacement_actual

Expected
labelplacement_expected

Or is there another way to this?

Thanks in advance

### PR DESCRIPTION
**Pull request by fosterbuster**
Fixes #1119.

### Checklist

- [ ] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

### Changes proposed in this pull request:

- Check if value is smaller than 0, if true place label below ColumnSeries
-
-

@oxyplot/admins

### CODE REVIEW

**Comment by objorke** [comment]
I am not allowed to contribute on open source at the moment (company regulations). 
@oxyplot/developers Can someone else handle this PR?

**Comment by objorke** [comment]
Thanks!
I will add an example.

**Comment by ProDInfo** [comment]
This commit has changed and revert to old code

**Comment by objorke** [comment]
@ProDInfo thanks for pointing this out! can you please make the PR?

**Pull request merged**
