### PR TITLE
Update changelog for 2.2.0

### PR DESCRIPTION
**Pull request by VisualMelon**
Changes to the changelog for 2.2.0. Went with 2.2.0 rather than 2.1.3 because of all the dependency changes and the couple of breaking changes; nothing too much to be excited about in this release.

Once finalised, will create branch release/v2.2.0 and push to nuget.

Would be nice to include https://github.com/oxyplot/oxyplot/pull/2099 but can always do a point release.

@oxyplot/admins

### CODE REVIEW

**Review by Jonarw — APPROVED** [review]

**Comment by Jonarw** [comment]
Maybe we can try and get #2099 merged and then do the release?

**Comment by VisualMelon** [comment]
That suits me. May be that we need to put out a point release to fix ImageSharp as it won't have been seriously tested, but that's OK with me.

**Comment by VisualMelon** [comment]
@Jonarw if you're happy with this, I'll try to get the release done in the next few hours (running the tests can take a while these days)

**Comment by VisualMelon** [comment]
Current develop pushed to https://www.myget.org/F/melonoxyplottesting as 2.2.0

**Comment by VisualMelon** [comment]
Checked that the 2.2.0 WPF package works, and that 2.2.0 Core works with Avalonia 2.1.0-Avalonia11

**Review by Jonarw — APPROVED** [review]

**Comment by VisualMelon** [comment]
Pushed

**Pull request merged**
