### PR TITLE
Optimized rendering performance of RectangleBarSeries

### PR DESCRIPTION
**Pull request by olegtarasov**
As part of #834 I optimized rendering performance of RectangleBarSeries. I've also installed StyleCop and validated my changes against the ruleset.

@oxyplot/admins

### CODE REVIEW

**Comment by objorke** [comment]
I have trigged a new build. Gitversion failed for unknown reason

**Comment by olegtarasov** [comment]
The build seems to fail from time to time with this exception:

    ERROR [04/04/16 19:50:14:43] An unexpected error occurred:
    System.Net.WebException: The remote server returned an error: (500) Internal Server Error.

It failed again :)

**Comment by objorke** [comment]
I think the problem is in gitversion. I have had time to check if it is an open issue over there...
https://github.com/GitTools/GitVersion/issues

**Comment by olegtarasov** [comment]
So are you going to merge this pull request? :)  The code seems to be fine.

**Comment by objorke** [comment]
Yes, the code seems to be ok. I will try to merge!

**Pull request merged**
