### PR TITLE
#729 Bugfix stack group labels fork

### PR DESCRIPTION
**Pull request by benjaminrupp**
Sorry for this second pull request. In my first request for #729 there are still some errors on the implementation of UpdateFromSeries in CategoryAxis. And cause I am relativlely new to git and github I have no idea how to change the first pull request.

I cleaned up the code also to be more familiar to the previous implementation.

Best regards

Benjamin

### CODE REVIEW

**Comment by objorke** [comment]
It should be possible to change the commit history of your branch and `git push -f` to update the PR
I really appreciate that you have created a lot of examples demonstrating the feature!
I am a bit concerned about the code in `CategoryAxis` - the current design looks wrong to me. The `CategoryAxis` should not be responsible for functionality of a series. I think the bar offsets and min/max values could be moved to the BarSeries/ColumnSeries, will create a new issue for this refactoring.

**Comment by benjaminrupp** [comment]
Hi objorke,

sorry for my late reply. I was busy.
I changed now my commit to be on top of develop branch.
Hope this is okay now.

I think refaktoring CategoryAxis is a really good idea.

Best

Benjamin

**Comment by objorke** [comment]
The build is still broken. I can have a look at refactoring CategoryAxis (#741).

**Comment by benjaminrupp** [comment]
I am not familiar with appVeyor. Can you tell me whats the problem?

In found the following in the console
ERROR [02/03/16 7:53:12:12] An unexpected error occurred:
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.GetResponse()
   at GitVersion.AppVeyor.GenerateSetVersionMessage(VersionVariables variables)
   at GitVersion.BuildServerBase.WriteIntegration(Action`1 writer, VersionVariables variables)
   at GitVersion.SpecifiedArgumentRunner.Run(Arguments arguments, IFileSystem fileSystem)
   at GitVersion.Program.VerifyArgumentsAndRun()

I have no idea what this means?

**Comment by objorke** [comment]
Currently, the build errors on AppVeyor seems to be related to the Xamarin projects. Not sure why, the Xamarin subscription should be valid. I will try to move the Xamarin projects to its own repository, I just need to find a good way to move all the git history.

**Comment by benjaminrupp** [comment]
I think you could copy your git repo and then rebase the complete solution and remove everythink accept the xamarin stuff. Then you can upload this stuff into a new remote. 
I never did anything like that but I have read something similar in https://progit.org/.
I think it was in chapter chapter "Git tools".

**Comment by objorke** [comment]
See my comment on #729. I think #741 should be solved first, then the functionality of #729 should be added in the BarSeries/ColumnSeries. The CategoryAxis should contain any code related to #729.
So - I don't want to accept this, since it makes #741 harder.

**Pull request closed without merging**
