### PR TITLE
fix not correct char

### PR DESCRIPTION
**Pull request by lwqwag**
Fixes the char not correct in vs for chinese

@oxyplot/admins

### CODE REVIEW

**Comment by VisualMelon** [comment]
Could you elaborate on the issue? I'm afraid I don't know anything about non-western script, but the degree symbol should be there.

**Comment by lwqwag** [comment]
> Could you elaborate on the issue? I'm afraid I don't know anything about non-western script, but the degree symbol should be there.

At first I don't know it's a  symbol because In Chinese  visual studio ,the symbol can't display correct like the image. 

For now ,I agree with you and close the pr. Thank you!

**Comment by VisualMelon** [comment]
Out of interest, which font do you use for the editor?

**Comment by lwqwag** [comment]
> Out of interest, which font do you use for the editor?

The text editor font is Luicida Sans Typewriter. I found the problem was that Chinese (language) version  visualstudio would select GB-2312 charset.

**Pull request closed without merging**
