### PR TITLE
Enable checked math. This is a test. Will close shortly.

### PR DESCRIPTION
**Pull request by shoelzer**
I'm doing this so I can submit a PR on Github and have AppVeyor run all the build tests. Let's see if anything breaks.

### CODE REVIEW

**Comment by tibel** [comment]
Hope you don't want to enable these checks in release mode. This will kill performance totally.

**Comment by shoelzer** [comment]
I was not planning to enable these checks in any build. I'm just curious to see if anything breaks.

Why do you think they would kill performance? I'm not saying you're wrong, but in my (limited) experience these checks are negligible except for tight loops doing math.

**Comment by tibel** [comment]
Thanks for clarification.
Saying that the checks are negligible means we have to profile if this is really the case.

OxyPlot as the name implies is a plotting library so nearly every arithmetic calculation is part of rendering or some user interaction. Said that the design goal if FPS (frames per second) and responsiveness to user actions.

I personally know no library that has the checks enabled.

**Comment by shoelzer** [comment]
Oh yes, I agree. I would definitely profile before proposing that these checks get turned on by default. Like I said, I'm just curious and poking around for bugs.

**Comment by objorke** [comment]
isn't it easier to just run the tests locally? ;-)

**Comment by shoelzer** [comment]
Perhaps. But then I would need to install NUnit and maybe other dependencies. I just haven't bothered doing that yet. I had noticed that that the tests run automatically when I push a PR so I just kept going with it.

I think I'm done with this experiment anyway. There are only three remaining test failures in this branch and I didn't find any real bugs. Kudos to both of you and the other OxyPlot devs!

**Pull request closed without merging**
