### PR TITLE
RectangleSeries (with mapping from ItemsSource)

### LINKED ISSUE #911: HeatMap and PolarHeatMap interpolation for non-uniform grids
### Feature description

The current implementation in HeatMapSeries assumes regularly spaced grid, using only the lower and upper ends of the axis being used and the number of data points.  For example, we set X0=0 and X1=10 and have 11 data points along that dimension, giving an assumed spacing of 1.  It would be nice if the interpolation algorithm could handle irregular spacing, as done by ContourSeries.

The same comment applies to PolarHeatMapSeries.

### PR DESCRIPTION
**Pull request by dynamatt**
Fixes #911 (partial).
### Checklist
- [x] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [ ] I have cleaned up the commit history (use rebase and squash)
### Changes proposed in this pull request:
- This is a partial fix for #911. 
- It adds the ability to bind a HeatMapSeries to an ItemsSource with a mapping that converts the objects in the ItemsSource to DataRect objects which are plotted on the HeatMap, similar to how DataPoint objects are plotted in a LineSeries.

@oxyplot/admins

### CODE REVIEW

**Comment by objorke** [comment]
it seems like the OxyPlot_NET40.csproj and OxyPlot_SL5.csproj have not been updated

**Comment by dynamatt** [comment]
Ooops. OK I'm on it.

**Comment by dynamatt** [comment]
Hi @objorke, I've updated the NET40 and SL5 projects as requested.

**Comment by objorke** [comment]
I started thinking - maybe this belongs to a new series `RectangleSeries`. I think it is a bit confusing to support both List<DataRect> and double[,] in the same series - they are very different structures which enables/disables a lot of the other properties in the class.

**Comment by dynamatt** [comment]
I agree. I've implemented this change here. Sorry about the mess of commits - I'm not really sure how to use squash and rebase properly...

**Comment by objorke** [comment]
No problem to let github handle the squashing!

**Comment by objorke** [comment]
I found quite a few things to comment do you want me to update the PR to avoid more iterations?

**Comment by dynamatt** [comment]
Yeah that would be good, thanks! Let me know if there's anything I can do.

**Comment by objorke** [comment]
I have rebased this code on the latest `develop` https://github.com/objorke/oxyplot/tree/features/rectangle-series

**Comment by dynamatt** [comment]
Hi @objorke ,
Could you please let me know if there's anything I can do to help get this into the development branch?
I've been trying to get the appveyor tests to pass but I think I need some help.
Matt

**Comment by objorke** [comment]
I am looking at this PR now!

**Comment by objorke** [comment]
I don't think this PR solves #911. 
From my understanding, #911 is about using the existing `HeatMapSeries` with `Data`, `ColumnCoordinates` and `RowCoordinates` properties as in `ContourSeries`.
This `RectangleSeries` also shares a lot of code with the existing `RectangleBarSeries`...
I will add the code, but add an issue about merging `RectangleSeries` and `RectangleBarSeries`.

**Comment by objorke** [comment]
Created #1060, which can be closed with this code :-)

**Comment by objorke** [comment]
I included your code in #1061!
Thanks for including example and wpf class!

**Comment by objorke** [comment]
Created #1062 regarding merging with `RectangleBarSeries`.

**Comment by objorke** [comment]
I merged #1061, containing squashed commits from this PR

**Comment by objorke** [comment]
thanks for contributing!

**Pull request closed without merging**
