### PR TITLE
Fixes for the NuSpec so that they can be packaged on Mac OS

### PR DESCRIPTION
**Pull request by mattleibow**

### CODE REVIEW

**Comment by mattleibow** [comment]
Temporarily closed as I am going to extend this to include the build script for the Xamarin CI server

**Comment by mattleibow** [comment]
This script was run on CI and pushed to NuGet successfully.

**Comment by objorke** [comment]
@mattleibow can the iOS/Android/Mac projects now be built on AppVeyor? Then we need to revert the changes to the nuspecs, right?

**Comment by mattleibow** [comment]
Yes and no. AppVeyor can only build iOS and Android libraries - but not the Mac ones yet. Also, this script allows for building the projects and NuGet on Mac OS (at least the bits that can). Windows can handle both separator types, so there is no problem with the forward slashes.

**Comment by objorke** [comment]
Thanks, then this change is OK.

**Comment by objorke** [comment]
Thanks for fixing this!

**Pull request merged**
