### PR TITLE
Fix #850

### LINKED ISSUE #850: LogarithmicAxis sometimes places major ticks outside of the axis range
### Steps to reproduce

1. Open the logarithmic axis tick calculation example
2. Pan the left axis (base 10) down a bit

### Expected behaviour

No major ticks should appear outside the axis limits.

### Actual behaviour
capture
Sometimes a candidate outside the axis range gets matched to a desired point inside the axis range, causing a major tick to be placed outside the range.

Easily fixed, will make a commit soon.

### PR DESCRIPTION
**Pull request by Jonarw**
Fixes #850 .

### Checklist

- [ ] I have included examples or tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file
- [x] I have cleaned up the commit history (use rebase and squash)

@oxyplot/admins

### CODE REVIEW

**Comment by tibel** [comment]
Please update change log

**Comment by Jonarw** [comment]
I was not sure whether to update the changelog for small fixes. Should I mention the two fixes for DateTimeAxis in the changelog as well?

**Comment by tibel** [comment]
I think the change log should be updated for all changes/fixes.

Pull #858 fixes an issue introduced by some other change (I think we don't need a change log for this) and #859 is similar.

**Comment by Jonarw** [comment]
Alright, done :)

**Comment by tibel** [comment]
Thanks

**Pull request merged**
