### PR TITLE
Nuget package cleanup

### PR DESCRIPTION
**Pull request by tibel**
- correct the package dependencies
- changed `OxyPlot` and `OxyPlot.Mobile` to be meta-packages that only reference other packages
- added `LICENSE` and `README.md` to all packages

### CODE REVIEW

**Comment by objorke** [comment]
Thanks for cleaning up the nuspecs!

**Comment by objorke** [comment]
It seems AppVeyor did not create the packages. I think there are some missing `"..\"` in the nuspecs

**Comment by objorke** [comment]
I'll try to fix this.

**Comment by objorke** [comment]
The relative paths of the Xamarin nuspecs are different, I think.

**Comment by tibel** [comment]
Sorry for that. I did some copy-paste and have not verified the paths.

**Comment by mattleibow** [comment]
@objorke @tibel Just to confirm. Are we going to be using separate packages for each platform?

**Comment by tibel** [comment]
@mattleibow The packages were already existing. The only change I did was to remove duplicates. So one assembly is only in one package. When you verify the changes you will see that some assemblies where part of multiple packages.

For example `OxyPlot.WP8.dll` was part of the packages:
- OxyPlot.WP8
- OxyPlot
- OxyPlot.Mobile

**Comment by objorke** [comment]
Is it a problem that the packages are not in the same build? (the Xamarin packages are built by Xamarin, not by AppVeyor)

**Comment by mattleibow** [comment]
@tibel I know about those... just wanted to check to see as @objorke was wanting to eliminate the large number of packages. Either way, doesn't really matter, other than I have to update my publish scripts.

**Comment by objorke** [comment]
@mattleibow @tibel Yes, I would think it would be nice to reduce the number of packages - it is confusing to see 19 packages in NuGet. I created #242 to clean up (#274 is about CI). Can we re-open #242 and discuss the best solution there?

**Comment by objorke** [comment]
1. Is it possible to create a package that includes both winforms, wpf, gtk and xwt assemblies (all for NET4x) and automatically adds only the relevant references? I think this was the reason why I created some of these packages.
2. Is package download size important? I guess having meta packages is good to reduce the size of the downloads.

**Comment by tibel** [comment]
Yes, you can put all in one package, BUT then you have to code install/remove of each assembly by hand in PowerShell (I would not try this; you loose nearly all nuget features). The package size is not so relevant (at least for me).

**Comment by mattleibow** [comment]
@tibel I agree with you. Separate the UI platforms and leave it up to the dev to pick what should be installed.

**Pull request merged**
